---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmChart
metadata:
  name: ols-basf
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm-charts/ols-basf
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: ols-basf
  interval: 10m0s
