apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  
  template:
    metadata:
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - args:
          - mongod
        image: mongo:3.2.9
        name: mongo
        ports:
          - containerPort: 27017
        resources: {}
        volumeMounts:
          - mountPath: /data/db
            name: ols-mongo-data
      restartPolicy: Always
      volumes:
        - name: ols-mongo-data
          persistentVolumeClaim:
            claimName: ols-mongo-data

