apiVersion: batch/v1
kind: Job
metadata:
  name: ols-indexer
spec:
  template:
    spec:
      containers:
      - name: ols-indexer
        image: ebispot/ols-indexer:stable
        env:
            - name: spring.data.mongodb.host
              value: mongo
            - name: spring.data.mongodb.uri
              value: mongodb://mongo/test
            - name: spring.data.solr.host
              value: http://solr:8983/solr
        volumeMounts:
            - mountPath: /mnt/neo4j
              name: ols-neo4j-data
            - mountPath: /mnt/downloads
              name: ols-downloads
      restartPolicy: Never
      volumes:
        - name: ols-neo4j-data
          persistentVolumeClaim:
            claimName: ols-neo4j-data
        - name: ols-downloads
          persistentVolumeClaim:
            claimName: ols-downloads
  backoffLimit: 4
