---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ols-basf
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev
  url: https://github.com/brunopma/OLS
