apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ols-basf
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/brunopma/OLS
  ref:
    branch: dev
  ignore: |
    # exclude all
    /*
    # include charts
     directory
    !/charts/