apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ols-basf
  namespace: ols-basf
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: ols-basf
  targetNamespace: ols-basf
  chart:
    git: git@github.com:brunopma/OLS.git
    path: helm-charts/ols-basf
    ref: dev
