apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ols-basf
  namespace: ols-basf
  annotations:
    fluxcd.io/automated: "true"
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm-charts/ols-basf
      version: '>=0.0.1 <1.0.0'
      sourceRef:
        kind: GitRepository
        name: ols-basf
        namespace: flux-system
      interval: 1m
  reconcileStrategy: Revision
  values:
    replicaCount: 1
