apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ols-web
  name: ols-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ols-web
  
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ols-web
    spec:
      containers:
        - env:
            - name: OLS_HOME
              value: /mnt/
            - name: ols.customisation.backgroundColor
              value: '#0080FF'
            - name: ols.customisation.backgroundImage
              value: /img/background_trial.jpg
            - name: ols.customisation.issuesPage
              value: https://github.com/EBISPOT/OLS/issues
            - name: ols.customisation.logo
              value: /img/OLS_logo_2017.png
            - name: ols.customisation.org
              value: EMBL-EBI
            - name: ols.customisation.short-title
              value: OLS
            - name: ols.customisation.supportMail
              value: ols-support@ebi.ac.uk
            - name: ols.customisation.title
              value: Ontology_Lookup_Service
            - name: ols.customisation.twitter
              value: https://twitter.com/EBIOLS
            - name: ols.customisation.web
              value: https://www.ebi.ac.uk/
            - name: spring.data.mongodb.host
              value: mongo
            - name: spring.data.solr.host
              value: http://solr:8983/solr
          image: ebispot/ols-web:v3.2.5-main-test
          name: ols-web
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /mnt/neo4j
              name: ols-neo4j-data
            - mountPath: /mnt/downloads
              name: ols-downloads
      restartPolicy: Always
      volumes:
        - name: ols-neo4j-data
          persistentVolumeClaim:
            claimName: ols-neo4j-data
        - name: ols-downloads
          persistentVolumeClaim:
            claimName: ols-downloads

